In [2]:
import numpy as np
print("Numpy è installato correttamente!")
print(f"Versione: {np.__version__}")

Numpy è installato correttamente!
Versione: 2.4.3


In [9]:
#esercizio 1
vett=np.array([2,3,5,7,11,13,17,19])
#----
print(vett>10) #stampa i booleani
print(vett[vett>10]) #stampa i numeri
#----
print(vett%2==0)
print(vett[vett%2==0])


[False False False False  True  True  True  True]
[11 13 17 19]
[ True False False False False False False False]
[2]


In [10]:
#esercizio 2
a=np.arange(1,21).reshape(4,5)
#----
b=a[[1,3], ]
c=a[[2], ]
#----
risultato_array= a/c
print(risultato_array)

[[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]
 [0.54545455 0.58333333 0.61538462 0.64285714 0.66666667]
 [1.         1.         1.         1.         1.        ]
 [1.45454545 1.41666667 1.38461538 1.35714286 1.33333333]]


In [ ]:
#esercizio 3
ARR=np.random.rand(10,3)
c=np.argmin(np.abs(ARR-0.5), axis=1)
ARR[np.arange(ARR.shape[0]),np.argmin(np.abs(ARR-0.5), axis=1)]

array([0.58403096, 0.46556514, 0.58673908, 0.41927536, 0.55842431,
       0.32430399, 0.77963546, 0.65124747, 0.27835463, 0.803954  ])

In [24]:
#esercizio 4
FitBit=np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])
m=np.min(FitBit)
print(m)
#----
M=np.max(FitBit)
print(M)
#----
new=FitBit>120
print(new)

def sintesi(arr):
    n_elem=arr.size
    n_giusti=sum(arr>120)
    return ((n_giusti/n_elem)*100)

print(sintesi(FitBit))

60
164
[False False False False  True  True  True  True  True  True  True  True
  True  True  True False False False False False False]
52.38095238095239


In [ ]:
#esercizio 5
stipendi=np.array([50000, 105250, 55000, 89000])
costo_tot=sum(stipendi)
print("all'inizio: ", costo_tot)
#----
stipendi[1]=stipendi[1]*1.15
print(stipendi)
#in questo modo arrotonda a int...
#----
stipendi=np.array([50000, 105250, 55000, 89000], dtype=float)
stipendi[1]=stipendi[1]*1.15
print(stipendi)
#----
stipendi[0]=stipendi[0]*1.2
print(stipendi)
#----
stipendi[2]=stipendi[2]*1.10
stipendi[3]=stipendi[3]*1.10
print(stipendi)
#----
costo_tot_f=sum(stipendi)
print("dopo gli aumenti: ", costo_tot_f)
aumento=costo_tot_f-costo_tot
print("l'aumento è estato di ", aumento, " euro per l'azienda")


all'inizio:  299250
[ 50000 121037  55000  89000]
[ 50000.  121037.5  55000.   89000. ]
[ 60000.  121037.5  55000.   89000. ]
[ 60000.  121037.5  60500.   97900. ]
dopo gli aumenti:  339437.5
l'aumento è estato di  40187.5  euro


In [ ]:
#esercizio 6


In [36]:
#esercizio 7
#la matrice ha età, reddito e anni di istruzione
survey_matrix = np.array([ [25, 40000, 10], [32, 52000, 12], [40, 63000, 14], [29, 47000, 11], [35, 58000, 13] ])
subMatrix_1=survey_matrix[survey_matrix[:, 2]>=12]
print(subMatrix_1)
#----
subMatrix_2=survey_matrix[survey_matrix[:, 2]>=12,1] #seleziono in particolare solo la colonna 1
print(subMatrix_2)
#----
reddito_medio=np.mean(subMatrix_2)
print(reddito_medio)


[[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]]
[52000 63000 58000]
57666.666666666664


In [41]:
#esercizio 8
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])
ages=ages[ages!=999]
MAX=np.max(ages)
print(MAX)


112


In [60]:
#esercizio 9
frase="In epoche passate, viveva una donna saggia che era molto orgogliosa dell antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, __ . Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __ . Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. Con un sorriso da un orecchio all altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza __ ! Ci fu grande gioia e celebrazione."
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]
MAX=len(lista_parole)
lista_frase=frase.strip().split(" ")
for i in range(5):
    n=np.random.randint(0,MAX+1)
    frase=frase.replace("__",lista_parole[n],1)
print(frase)



In epoche passate, viveva una donna saggia che era molto orgogliosa dell antico SERBATOIO che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il VARIANTE come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, FULMINE . Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un PROVA . Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. Con un sorriso da un orecchio all altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza VARIANTE ! Ci fu grande gioia e celebrazione.
